"*.{js,mjs,jsx,ts,tsx}":
    - eslint --fix
    - prettier --write

"*.{jsx,tsx}":
    - stylelint --fix

"*.{css,scss,html}":
    - stylelint --fix
    - prettier --write

"*.{json,md,yaml,yml}":
    - prettier --write
